Repository sparkfabrik/spark-k8s-deployer, pull requests merged in 2025-03, with the labels that each got.

#273 platform/#3217: add Workload identity federation logic for gcp
  templates/.gitlab-ci-template.yml
  templates/functions/gcp-wif.yml
  templates/functions/gitlab-helper-functions.yml
Labels: Review effort 3/5

#274 paltform/#3217: remove shell dependency in output printing.
  templates/functions/gcp-wif.yml
Labels: Review effort 1/5

#275 Fix dependecies between templates
  templates/.gitlab-ci-template.yml
Labels: Review effort 1/5

#277 platform/#3217: add gcloud_wif function
  templates/functions/gcp-wif.yml
Labels: Review effort 2/5

#278 platform/#3217: disable WIF by default
  templates/functions/gcp-wif.yml
Labels: Review effort 2/5

#279 platform/#3217: remove function
  templates/functions/gcp-wif.yml
  templates/functions/gitlab-helper-functions.yml
Labels: Review effort 1/5

#281 refs platform/#3217: fix sh error
  templates/.gitlab-ci-template.yml
  templates/functions/gcp-wif.yml
Labels: Review effort 2/5
